# Generated by Django 4.0.3 on 2022-03-06 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('opis', models.TextField()),
                ('zdjecie', models.ImageField(upload_to='uploads/')),
                ('ilosc_w_magazynie', models.IntegerField(default=0)),
                ('cena', models.DecimalField(decimal_places=2, default=1.00, max_digits=7)),
                ('data_dodania', models.DateTimeField(auto_now_add=True)),
                ('data_modyfikacji', models.DateTimeField(auto_now_add=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklepApp.kategoria')),
            ],
        ),
    ]
