# Generated by Django 4.0.3 on 2022-03-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0002_remove_produkt_cena_remove_produkt_zdjecie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, default=1.00, max_digits=7),
        ),
        migrations.AddField(
            model_name='produkt',
            name='zdjecie',
            field=models.ImageField(default='abc', upload_to='uploads/'),
        ),
    ]
