# Generated by Django 4.0.3 on 2022-03-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0003_produkt_cena_produkt_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='cena',
            field=models.DecimalField(decimal_places=2, max_digits=7, default=1.00),
        ),
    ]
