# Generated by Django 4.0.3 on 2022-03-06 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0006_adres_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='kategoria',
            new_name='kategoria_id',
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=100)),
                ('nazwisko', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=100)),
                ('adres_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklepApp.adres')),
                ('email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklepApp.email')),
            ],
        ),
        migrations.CreateModel(
            name='Koszyk_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zamowienia', models.IntegerField()),
                ('produkt', models.ManyToManyField(to='sklepApp.produkt')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sklepApp.user')),
            ],
        ),
    ]
