# Generated by Django 4.0.3 on 2022-03-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0007_rename_kategoria_produkt_kategoria_id_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Koszyk_logout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_zamowienia', models.IntegerField()),
                ('produkt', models.ManyToManyField(to='sklepApp.produkt')),
            ],
        ),
    ]
