# Generated by Django 4.0.3 on 2022-03-06 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0008_koszyk_logout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produkt',
            old_name='kategoria_id',
            new_name='kategoria',
        ),
    ]
