# Generated by Django 4.0.3 on 2022-03-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0010_rename_kategoria_produkt_kategoria_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='data_dodania',
            field=models.DateTimeField(),
        ),
    ]
