# Generated by Django 4.0.3 on 2022-03-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0011_alter_produkt_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='zdjecie',
            field=models.ImageField(default='abc', null=True, upload_to='uploads/'),
        ),
    ]
