# Generated by Django 4.0.3 on 2022-03-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sklepApp', '0012_alter_produkt_zdjecie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkt',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
